import { eraArray } from "../../../config/eras"
import { useTranslation } from "react-i18next"
import { parseGuideLinks } from "../../utilities/parseGuideLinks"

export default function OverviewGuide({ empire }) {
	const { t } = useTranslation(["guide", "eras"])
	const eraName = eraArray[empire.era].name.toLowerCase()

	return (
		<div>
			<h2>{t("guide:guide.content.overview.title")}</h2>
			<p>{parseGuideLinks(t("guide:guide.content.overview.description"))}</p>

			<h3>{t("guide:guide.content.overview.sections.empire.title")}</h3>
			<dl>
				<dt>
					{t(
						"guide:guide.content.overview.sections.empire.stats.turnsUsed.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.empire.stats.turnsUsed.description",
						),
					)}
				</dd>
				<dt>
					{t("guide:guide.content.overview.sections.empire.stats.money.name")}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.empire.stats.money.description",
						),
					)}
				</dd>
				<dt>
					{t("guide:guide.content.overview.sections.empire.stats.rank.name")}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.empire.stats.rank.description",
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.empire.stats.netWorth.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.empire.stats.netWorth.description",
							{
								foodType: t(`eras:eras.${eraName}.food`),
							},
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.empire.stats.population.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.empire.stats.population.description",
							{
								peasantName: t(`eras:eras.${eraName}.peasants`),
							},
						),
					)}
				</dd>
				<dt>
					{t("guide:guide.content.overview.sections.empire.stats.race.name")}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.empire.stats.race.description",
						),
					)}
				</dd>
				<dt>
					{t("guide:guide.content.overview.sections.empire.stats.era.name")}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.empire.stats.era.description",
						),
					)}
				</dd>
			</dl>

			<h3>{t("guide:guide.content.overview.sections.agriculture.title")}</h3>
			<dl>
				<dt>
					{t(
						"guide:guide.content.overview.sections.agriculture.stats.production.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.agriculture.stats.production.description",
							{
								farmType: t(`eras:eras.${eraName}.bldfood`),
								foodType: t(`eras:eras.${eraName}.food`),
							},
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.agriculture.stats.consumption.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.agriculture.stats.consumption.description",
							{
								peasantName: t(`eras:eras.${eraName}.peasants`),
								wizardType: t(`eras:eras.${eraName}.trpwiz`),
								foodType: t(`eras:eras.${eraName}.food`),
							},
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.agriculture.stats.net.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.agriculture.stats.net.description",
							{
								foodType: t(`eras:eras.${eraName}.food`),
							},
						),
					)}
				</dd>
			</dl>

			<h3>{t("guide:guide.content.overview.sections.other.title")}</h3>
			<dl>
				<dt>
					{t(
						"guide:guide.content.overview.sections.other.stats.exploration.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.other.stats.exploration.description",
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.other.stats.blackMarket.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.other.stats.blackMarket.description",
						),
					)}
				</dd>
				<dt>
					{t("guide:guide.content.overview.sections.other.stats.luck.name")}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.other.stats.luck.description",
							{
								foodType: t(`eras:eras.${eraName}.food`),
								runeType: t(`eras:eras.${eraName}.runes`),
							},
						),
					)}
				</dd>
			</dl>

			<h3>{t("guide:guide.content.overview.sections.landDivision.title")}</h3>
			<p>
				{parseGuideLinks(
					t("guide:guide.content.overview.sections.landDivision.description"),
				)}
			</p>

			<h3>{t("guide:guide.content.overview.sections.finances.title")}</h3>
			<dl>
				<dt>
					{t(
						"guide:guide.content.overview.sections.finances.stats.perCapIncome.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.finances.stats.perCapIncome.description",
							{
								peasantName: t(`eras:eras.${eraName}.peasants`),
							},
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.finances.stats.income.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.finances.stats.income.description",
							{
								peasantName: t(`eras:eras.${eraName}.peasants`),
							},
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.finances.stats.expenses.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.finances.stats.expenses.description",
							{
								barracksType: t(`eras:eras.${eraName}.bldcost`),
							},
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.finances.stats.loanPayment.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.finances.stats.loanPayment.description",
						),
					)}
				</dd>
				<dt>
					{t("guide:guide.content.overview.sections.finances.stats.net.name")}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.finances.stats.net.description",
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.finances.stats.savingsBalance.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.finances.stats.savingsBalance.description",
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.finances.stats.loanBalance.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.finances.stats.loanBalance.description",
						),
					)}
				</dd>
			</dl>

			<h3>{t("guide:guide.content.overview.sections.military.title")}</h3>
			<p>
				{parseGuideLinks(
					t("guide:guide.content.overview.sections.military.description"),
				)}
			</p>
			<dl>
				<dt>
					{t(
						"guide:guide.content.overview.sections.military.stats.offensivePower.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.military.stats.offensivePower.description",
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.military.stats.defensivePower.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.military.stats.defensivePower.description",
						),
					)}
				</dd>
			</dl>

			<h3>{t("guide:guide.content.overview.sections.relations.title")}</h3>
			<dl>
				<dt>
					{t("guide:guide.content.overview.sections.relations.stats.clan.name")}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.relations.stats.clan.description",
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.relations.stats.enemies.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.relations.stats.enemies.description",
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.relations.stats.offensiveActions.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.relations.stats.offensiveActions.description",
						),
					)}
				</dd>
				<dt>
					{t(
						"guide:guide.content.overview.sections.relations.stats.defenses.name",
					)}
				</dt>
				<dd>
					{parseGuideLinks(
						t(
							"guide:guide.content.overview.sections.relations.stats.defenses.description",
						),
					)}
				</dd>
			</dl>
		</div>
	)
}
